alias: Défi Hilo Recovery PM
description: "Permet de gérer la période de reprise PM/Manages the PM recovery phase of a Hilo Challenge"
mode: single
triggers:
  - entity_id:
      - sensor.defi_hilo
    to: recovery
    trigger: state
    from: reduction
  - at: "20:00:00"
    trigger: time
conditions:
  - condition: time
    before: "20:05:00"
    after: "19:55:00"
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.defi_hilo
        state:
          - reduction
      - condition: state
        entity_id: sensor.defi_hilo
        state:
          - recovery
actions:
  - data:
      temperature: 18
    target:
      entity_id:
        - climate.thermostat_cuisine
    action: climate.set_temperature
  - metadata: {}
    data: {}
    target:
      entity_id: switch.prise_echangeur_d_air
    action: switch.turn_on
