alias: Défi Hilo Ancrage PM
description: "Permet de gérer la période d'ancrage PM d'un défi Hilo/Manages the PM anchor phase of a Hilo Challenge"
mode: single
triggers:
  - entity_id:
      - sensor.defi_hilo
    to:
      - appreciation
    trigger: state
    id: Sensor
    from:
      - scheduled
    for:
      hours: 1
      minutes: 0
      seconds: 0
  - entity_id:
      - sensor.defi_hilo
    to:
      - appreciation
    trigger: state
    id: Sensor
    from:
      - completed
    for:
      hours: 1
      minutes: 0
      seconds: 0
conditions:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{'pm' in state_attr('sensor.defi_hilo','next_events')[0]['period'] }}"
      - condition: template
        value_template: >-
          {{ (state_attr('sensor.defi_hilo',
          'next_events')[0]['phases']['preheat_start'] |
          as_datetime).strftime('%Y-%m-%d') == now().strftime('%Y-%m-%d') }}
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.defi_hilo
        state: appreciation
      - condition: state
        entity_id: sensor.defi_hilo
        state: scheduled
      - condition: state
        entity_id: sensor.defi_hilo
        state: pre_cold        
  - condition: time
    after: "11:55:00"
    before: "12:05:00"
actions:
  - action: climate.set_temperature
    metadata: {}
    data: {}
    target:
      entity_id: climate.thermostat_cuisine
