alias: Défi Hilo Réduction PM
description: "Permet de gérer la période de réduction PM/Manages the PM reduction phase of a Hilo Challenge"
mode: single
triggers:
  - entity_id:
      - sensor.defi_hilo
    to: reduction
    id: Sensor
    trigger: state
    from: pre_heat
  - at: "16:00:00"
    trigger: time
conditions:
  - condition: time
    before: "16:05:00"
    after: "15:55:00"
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.defi_hilo
        state: pre_heat
      - condition: state
        entity_id: sensor.defi_hilo
        state: reduction
actions:
  - data:
      temperature: 15
    target:
      entity_id:
        - climate.thermostat_cuisine
    action: climate.set_temperature
