# From https://github.com/home-assistant/core/blob/dev/Dockerfile.dev
# This gets us an environment as close as possible to the default Home Assistant
# dev environment for custom component development.

FROM mcr.microsoft.com/devcontainers/python:3-3.14-bookworm

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    # Libraries needed by Home Assistant to simulate a real environment
    bluez \
    ffmpeg \
    libudev-dev \
    libavformat-dev \
    libavcodec-dev \
    libavdevice-dev \
    libavutil-dev \
    libgammu-dev \
    libswscale-dev \
    libswresample-dev \
    libavfilter-dev \
    libpcap-dev \
    libturbojpeg0 \
    libyaml-dev \
    libxml2 \
    git \
    cmake \
    tmux \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:latest /usr/local/bin/go2rtc /bin/go2rtc

# Install uv and uvx
RUN pip3 install --no-cache-dir uv

USER vscode
ENV VIRTUAL_ENV="/home/vscode/.local/ha-venv"
ENV UV_PROJECT_ENVIRONMENT="/home/vscode/.local/ha-venv"
RUN uv venv --python 3.14 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /tmp/build

# Pre-install dependencies into venv
COPY pyproject.toml README.md ./
RUN uv sync --no-install-project --group test

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL=/bin/bash
