#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/hilo
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Check if python-hilo exists and install it in development mode
if [[ -d "/workspaces/python-hilo/pyhilo" ]]; then
    echo "Installing custom version of python-hilo..."
    pip install -e "/workspaces/python-hilo"
    SKIP_PACKAGES="--skip-pip-packages python-hilo"
else
    echo "Using PyPI version of python-hilo..."
    SKIP_PACKAGES=""
fi

# Start Home Assistant
hass --config "${PWD}/config" --debug ${SKIP_PACKAGES}
