#!/usr/bin/env bash
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."
python3 -m pip install --requirement requirements.txt
