name: Manage labels

on:
  push:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.3.0
        with:
          configuration-path: .github/labels.yml
          skip-delete: true
