name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
    steps:
      - uses: actions/checkout@v4
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build Assets
        run: |
          cargo build --release --target ${{ matrix.target }}
          tar -C target/${{ matrix.target }}/release/ -czvf gengo-${{ matrix.target }}.zip gengo${{ runner.os == 'Windows' && '.exe' || '' }}
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
      - name: Upload Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3
        with:
          path: '*.zip'
