            - name: Upload Asset
  # You may pin to the exact commit or the version.
  # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
  uses: PeerXu/upload-asset@v1
  with:
    # which file to upload
    file:
    custom_component/hilo
    # file suffix
    suffix: # optional, default is .tar.gz
    .zip
    # which operating system platform for file to execute
    os: # optional, default is 
    # which architecture platform for file to execute
    arch: # optional, default is 
    # upload file to asset with tag version
    with_tag: # optional, default is true
    # upload file to asset with hash in sha1 algorithm
    with_sha1: # optional, default is true
          
